"""Compatibility tests for rosbags-generated MCAP files with rebake.

This module verifies that MCAP files generated by the rosbags library
can be correctly read by rebake's Rosbag2Ingestor.
"""

from __future__ import annotations

from pathlib import Path


class TestMcapCompatibility:
    """Tests for verifying rosbags-rebake MCAP compatibility."""

    def test_ingestor_reads_generated_mcap(
        self, test_mcap_path: Path, test_ingestor
    ) -> None:
        """Verify that rebake can read an MCAP file generated by rosbags."""
        # Act
        topics, metadata, image_data, _ = test_ingestor.ingest(str(test_mcap_path))

        # Assert - Should have data
        assert len(topics) > 0, "No topics found in ingested MCAP"

    def test_joint_states_topic_present(
        self, test_mcap_path: Path, test_ingestor
    ) -> None:
        """Verify /joint_states topic is correctly ingested."""
        # Arrange & Act
        topics, metadata, image_data, _ = test_ingestor.ingest(str(test_mcap_path))

        # Assert
        assert "/joint_states" in topics, f"Expected /joint_states in {topics.keys()}"

        # Get the data and verify structure
        table = topics["/joint_states"]
        assert table.num_rows == 10, f"Expected 10 rows, got {table.num_rows}"

        # Verify expected columns exist
        column_names = table.schema.names
        assert "timestamp_ns" in column_names
        assert "publish_timestamp_ns" in column_names
        assert "name" in column_names
        assert "position" in column_names

    def test_image_topic_present(self, test_mcap_path: Path, test_ingestor) -> None:
        """Verify /camera/image_raw topic is correctly ingested."""
        # Arrange & Act
        topics, metadata, image_data, _ = test_ingestor.ingest(str(test_mcap_path))

        # Assert
        assert "/camera/image_raw" in topics, (
            f"Expected /camera/image_raw in {topics.keys()}"
        )

        # Image data should be in separate storage
        assert image_data is not None, "Image data should not be None"
        assert "/camera/image_raw" in image_data, "Image topic not in image_data"

        frames = image_data["/camera/image_raw"]
        assert len(frames) == 10, f"Expected 10 frames, got {len(frames)}"

    def test_camera_info_topic_present(
        self, test_mcap_path: Path, test_ingestor
    ) -> None:
        """Verify /camera/camera_info topic is correctly ingested."""
        # Arrange & Act
        topics, metadata, image_data, _ = test_ingestor.ingest(str(test_mcap_path))

        # Assert
        assert "/camera/camera_info" in topics

        table = topics["/camera/camera_info"]
        assert table.num_rows == 10

        # Verify camera info fields
        column_names = table.schema.names
        assert "width" in column_names
        assert "height" in column_names

    def test_tf_topic_present(self, test_mcap_path: Path, test_ingestor) -> None:
        """Verify /tf topic is correctly ingested."""
        # Arrange & Act
        topics, metadata, image_data, _ = test_ingestor.ingest(str(test_mcap_path))

        # Assert
        assert "/tf" in topics, f"Expected /tf in {topics.keys()}"

        table = topics["/tf"]
        assert table.num_rows > 0

    def test_all_expected_topics_present(
        self, test_mcap_path: Path, test_ingestor
    ) -> None:
        """Verify all expected topics are ingested."""
        # Arrange & Act
        topics, metadata, image_data, _ = test_ingestor.ingest(str(test_mcap_path))

        # Assert
        topic_names = set(topics.keys())
        expected = {"/joint_states", "/camera/image_raw", "/camera/camera_info", "/tf"}

        assert expected.issubset(topic_names), (
            f"Missing topics: {expected - topic_names}. Found: {topic_names}"
        )

    def test_timestamps_are_sequential(
        self, test_mcap_path: Path, test_ingestor
    ) -> None:
        """Verify that timestamps are in sequential order."""
        # Arrange & Act
        topics, metadata, image_data, _ = test_ingestor.ingest(str(test_mcap_path))

        # Assert - Check joint_states timestamps
        table = topics["/joint_states"]
        timestamps = table.column("timestamp_ns").to_pylist()

        for i in range(1, len(timestamps)):
            assert timestamps[i] > timestamps[i - 1], (
                f"Timestamps not sequential at index {i}: "
                f"{timestamps[i - 1]} >= {timestamps[i]}"
            )

    def test_joint_positions_vary_over_time(
        self, test_mcap_path: Path, test_ingestor
    ) -> None:
        """Verify joint positions change across frames (not all zeros)."""
        # Arrange & Act
        topics, metadata, image_data, _ = test_ingestor.ingest(str(test_mcap_path))

        # Assert
        table = topics["/joint_states"]
        positions = table.column("position").to_pylist()

        # At least some positions should be non-zero
        all_values = []
        for pos_list in positions:
            if pos_list:
                all_values.extend(pos_list)

        assert any(v != 0.0 for v in all_values), "All joint positions are zero"
